version: '3.8'

services:
  postgres-diploma:
    image: postgres:15-alpine
    container_name: diploma_postgres
    environment:
      POSTGRES_DB: diploma_db
      POSTGRES_USER: itmo_user
      POSTGRES_PASSWORD: itmo_pass
    ports:
      - "5435:5432"
    volumes:
      - diploma_postgres_data:/var/lib/postgresql/data

volumes:
  diploma_postgres_data:
