spring.datasource.url=jdbc:postgresql://localhost:5435/diploma_db
spring.datasource.username=itmo_user
spring.datasource.password=itmo_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/diploma/db.changelog-master.yaml
server.port=8080
app.security.jwt.secret=dnVNaW81NXNjaWdtRkdFZ2FhVXQ4eHlLNEZlRGNhYmFTOGF0Mjk
app.security.jwt.access-token-ttl-minutes=120
