spring.datasource.url=jdbc:postgresql://localhost:5433/homework5db
spring.datasource.username=itmo_user
spring.datasource.password=itmo_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.main.web-application-type=none
spring.liquibase.enabled=false